services:
  api:
    build: .
    ports:
    - "8080:8080"
    env_file:
      - .env

    develop:
      watch:
        - action: rebuild
          path: build/libs/
    depends_on:
      db:
        condition: service_started
    networks:
      - db_p2p_network

  db:
    build: ./db
    restart: always
    container_name: db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: db_p2p
    networks:
      - db_p2p_network
    volumes:
      - p2p_db_volume:/var/lib/mysql
volumes:
  p2p_db_volume:

networks:
  db_p2p_network:
