spring.datasource.url=jdbc:postgresql://db:5432/db_p2p
spring.datasource.username=root
spring.datasource.password=root


spring.devtools.restart.enabled=true
spring.devtools.restart.additional-paths=src/main/java/

