spring.datasource.url=jdbc:postgres://${MYSQL_HOST:localhost}:3306/db_p2p
spring.datasource.username=${SPRING_DATASOURCE_USER:root}
spring.datasource.password=${SPRING_DATASOURCE_PASS:root}

logging.level.org.springframework.web=INFO

