spring.application.name=spring-p2pcraft
springdoc.api-docs.path=/api-docs
springdoc.writer-with-order-by-keys=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.profiles.active=dev
spring.threads.virtual.enabled=true